version: '3'

services:
  api:
    build: .
    command: sh -c "python manage.py"
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bank
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - 5432



